export const STORIES_FETCHED = 'STORIES_FETCHED';
export const STORIES_LOADING = 'STORIES_LOADING';
export const STORIES_FAILD = 'STORIES_FAILD';

export const STORY_CREATED = 'STORY_CREATED';
export const STORY_CREATION_FAILED = 'STORY_CREATION_FAILED';

export const STORY_UPDATED = 'STORY_UPDATED';
export const STORY_DELETED = 'STORY_DELETED';
export const STORY_LIKED = 'STORY_LIKED';